version: '3'

services:
  httpd:
    build:
      context: ../../
      dockerfile: config/docker/dockerfiles/httpd/Dockerfile
    volumes:
      - ../../drupal/:/usr/local/apache2/htdocs
    ports:
      - 80
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.httpd.rule=Host(`drupal.wework`)"

  php:
    build:
      context: ../../
      dockerfile: config/docker/dockerfiles/php/Dockerfile
    volumes:
      - ../../drupal/:/var/www/html

  mysql:
    build:
      context: ../../
      dockerfile: config/docker/dockerfiles/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    restart: always
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`drupal.pma`)"

  varnish:
    image: varnish:6.2
    volumes:
      - ../../config/varnish/vcl:/etc/varnish/
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.varnish.rule=Host(`drupal.varnish`)"

  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"