FROM httpd:2.4

#WORKDIR /var/www/html

COPY config/docker/dockerfiles/httpd/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY config/docker/dockerfiles/httpd/httpd.conf /usr/local/apache2/conf/httpd.conf